dataset: 'src/data/aps_failure/aps_failure_training_set.csv'
classname: class
# classname: consensus
classifier: naiveBays
nanStrategy: most_frequent
balancingStrategy: notBalanced
rescaler: normalize
covarianceThreshold: 0.95
patternMining: False
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
clustering: False
clusterParams:
  nclusters: 2
