name: DS2NaiveBaysBalancingTest
optimize: False       # Turns optimizer mode on and off
seq: False            # Turns sequential mode on and off
plot: ['seq']            # Plot modes to activate: single, seq, only
conf: src/config.yaml
confSeq: src/configSeq_RandForest.yaml
confPlot: plotConfig.yaml
outputDir: src\output\
debug: True
optimizer:
  numTrials: 30
  numJobs: 1
successString: ' - finished'
