name: rand forest 1st
optimize: False       # Turns optimizer mode on and off
seq: True             # Turns sequential mode on and off
plot: ['only']            # Plot modes to activate: single, seq, only
conf: src/config.yaml
confSeq: src/configSeq_RandForest.yaml
confPlot: plotConfig.yaml
outputDir: src\output\
debug: False
optimizer:
  numTrials: 30
  numJobs: 1
successString: ' - finished'
