name: DBscan vary eps
optimize: False       # Turns optimizer mode on and off
seq: True             # Turns sequential mode on and off
plot: ['seq']            # Plot modes to activate: single, seq, only
conf: src/config.yaml
confSeq: src/configSeq.yaml
confPlot: plotConfig.yaml
outputDir: src\output\
debug: False
optimizer:
  numTrials: 30
  numJobs: 1
successString: ' - finished'
