seqLogConversion: 'yaml,json-Csv'
logFile: output.csv
dpi: 500
ys: [
     #  [ ['homogeneity_score' ,'silhouette'],['ad_rand_score'], ['adjusted_mutual_info_score'], ['mutual_info_score'], ['normalized_mutual_info_score'], ['homogeneity_score'], ['completeness_score'], ['v_measure_score'], ['silhouette']],
      [['avg_lift', 'avg_confidence', 'avg_support']]
    ]


plotSingleParams:
  type: ['line',]
  level: 'localCSV'
  yAxes: ['Sensitivity', 'Specificity']

plotSeqParams:
  type: ['line']      # line, scatter scatterNx
  level: 'localCSV'
  # Shared
  #ymax: 1.3
  #ymin: 0
  # Only Line
  yLabelsLine: ['']
  annotations: True
  yAxes:  ['']
  pallets: False

  # OnlyScatter
  yLabelsScatter: ['']
  distanceToLabel: 0.15

  # Only Box
  yLabelsBox: ['', '']
  yAxesBox: ['Sensitivity', 'Specificity']

plotOnlyParams:
  dir: 'speech\knn(uniform, chebychev) - balancing - n_neighbors'
  type: ['scatter', 'scatterNx', 'box']    # line, scatter, scatterNx
  level: 'fetchCSV'    # localCSV, fetchCSV
  # Shared
  ymax: 1.3
  ymin: 0
  # Only Line
  yLabelsLine: ['Not Balanced', 'Randomly Undersample', 'SMOTE'] # fixme - careful with the order of directories
  annotations: True
  yAxes:  ['', 'Sensitivity', 'Specificity']
  pallets: True
  joinYToLabel: [True, False, False]
  # OnlyScatter
  yLabelsScatter: [['Not Balanced'], ['Randomly Undersample'], ['SMOTE']] # fixme - careful with the order of directories
  distanceToLabel: 0.15
  yAxesBox:  ['Sensitivity', 'Specificity']



# ['Not Balanced', 'Randomly Undersample', 'SMOTE']
# ['chebyshev', 'euclidean', 'manhattan']
# [['Sensitivity', 'Specificity'], [], []]
# [['Accuracy Test set', 'Accuracy Train set']]
# [['Entropy'], ['Gini']]

