seqLogConversion: 'yaml,json-Csv'
logFile: output.csv
dpi: 500

xSingle: 'index'

ys: [
      [['ad_rand_score', 'silhouette']]
    ]
#ys: [
#      [['sensitivity', 'specificity'], ['sensitivity'], ['specificity'], ['accuracy', 'accuracyTrain']],
#      [['sensitivity', 'specificity']],
#      [['sensitivity_kfoldVals'], ['specificity_kfoldVals']]
]
# ys: [['ad_rand_score', 'silhouette']]]
# ys: [
#      [['inertia', 'ad_rand_score', 'silhouette'], ['inertia'], ['ad_rand_score', 'silhouette']]
#    ]


plotSingleParams:
  type: ['line',]
  level: 'localCSV'
  yAxes: ['Sensitivity', 'Specificity']

plotSeqParams:
  type: ['line', 'scatter', 'box']      # line, scatter scatterNx
  level: 'localCSV'
  # Shared
  ymax: 1.3
  ymin: 0

  # Only Line
  yLabelsLine: [['Sensitivity', 'Specificity'], [''], [''], ['Test', 'Train']]
  # yLabelsLine: [[''], ['']]
  annotations: True
  # yLabelsLine: [['Adj Rand Index', 'Silhouette']]
  yAxes:  ['', 'Sensitivity', 'Specificity', '']
  # yAxes:  ['', 'Inertia', '']

  pallets: False

  # OnlyScatter
  yLabelsScatter: ['']
  distanceToLabel: 0.15

  # Only Box
  yLabelsBox: ['']
  # yAxesBox: ['Sensitivity', 'Specificity']


x: n_estimators # used for plot only mode.

plotOnlyParams:
  level: fetchCSV
  dir: 'seq - rand forest 2nd/rF(gini) - [n_estimators, max_depth]'
  type: ['line', 'scatter', 'box']    # line, scatter, scatterNx
  # Shared
  ymax: 1.3
  ymin: 0
  # Only Line
  annotations: True
  joinYToLabel: [True, False, False]
  yAxes:  ['', 'Sensitivity', 'Specificity', '']
  yLabelsLine:  [['depth 10', 'depth 20', 'depth 30'],
                 ['depth  10', 'depth 20', 'depth 30'],
                 ['depth  10', 'depth 20', 'depth 30']]
  pallets: True

  # OnlyScatter
  distanceToLabel: 0.15
  yLabelsScatter:  ['depth 10', 'depth 20', 'depth 30']

  yLabelsBox:  ['depth 10', 'depth 20', 'depth 30']
  yAxesBox:  ['Sensitivity', 'Specificity']

