seqLogConversion: 'yaml,json-Csv'
dpi: 500
logFile: output.csv

# -- Line ---
# x: ['correlationThreshold', 'correlationThreshold', 'correlationThreshold']
x: ['n_neighbors', 'n_neighbors', 'n_neighbors']
# x: ['max_depth', 'max_depth', 'max_depth']

ys: [['sensitivity', 'specificity'], ['sensitivity'], ['specificity']]
# ys: [['accuracy', 'accuracyTrain']]

# -- Scatter --
# x: ['correlationThreshold']
# x: ['n_neighbors']
# x: ['max_depth']
# x: ['balancingStrategy',]
# ys: [['sensitivity', 'specificity']]

plotSingleParams:
  type: ['line']
  level: 'localCSV'
  yAxes: ['Sensitivity', 'Specificity']

plotSeqParams:
  level: 'localCSV'
  type: ['line']  # line, scatter
  yAxes: ['', 'Sensitivity', 'Specificity']
  # yLabels: ['chebyshev', 'euclidean', 'manhattan']  # fixme - careful with the order of directories
  yLabels: [['Sensitivity', 'Specificity'], [], []] # fixme - careful with the order of directories
  # yLabels: [['Accuracy Test set', 'Accuracy Train set']] # fixme - careful with the order of directories
  ymax: 1
  ymin: 0
  annotations: True
  pos: 0.2


plotOnlyParams:
  dir: 'speech\dT(gini) - balancing - max_depth'
  type: ['scatter', 'scatterNx']    # line, scatter, scatterNx
  # type: ['scatter', 'scatterNx']    # line, scatter, scatterNx
  level: 'fetchCSV'    # localCSV, fetchCSV
  yLabels: [
            ['Not Balanced'],
            ['Randomly Undersample'],
            ['SMOTE'],
          ]  # fixme - careful with the order of directories
  # yLabels: [['Sensitivity', 'Specificity'], [], []] # fixme - careful with the order of directories
  # yLabels: [['Entropy'], ['Gini']]
  # yLabels: [['Accuracy Test set', 'Accuracy Train set']]
  yAxes: ['', 'Sensitivity', 'Specificity']

  ymax: 1.3
  ymin: 0
  pallets: True
  annotations: True
  joinYToLabel: [True, False, False]
  distanceToLabel: 0.15
