configs:
  - name: KNN(uniform, smote) - [distance, n_neighbors]
    variationsWithin:
      - name: classifierParams
        subName: metric
        values: [euclidean, chebyshev, manhattan]
      - name: classifierParams
        subName: n_neighbors
        values: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    priorityLine: [metric, n_neighbors]
    unifyByRecursionLevels: [1, 0]
    changedToHigherDimPlot:
      level: fetchCSV
      pallets: True
      joinYToLabel: [True, False, False]
      yLabelsLine:  [['Euclidean', 'Chebyshev', 'Manhattan'],
                     ['Euclidean', 'Chebyshev', 'Manhattan'],
                     ['Euclidean', 'Chebyshev', 'Manhattan']]
      yLabelsBox:  ['Euclidean', 'Chebyshev', 'Manhattan']
      yLabelsScatter:  ['Euclidean', 'Chebyshev', 'Manhattan']
    classifier: KNN
    classifierParams:
      weights: uniform
    dataset: 'src/data/covtype.data'
    classname: class
    nanStrategy: most_frequent
    balancingStrategy: smote
    rescaler: normalize
    correlationThreshold: 1
    PCA: False
    dataSplitMethod: 'kfold'
    kFold: 10
    clustering: False
    patternMining: False
    plotX: 'n_neighbors'
