configs:
   - name: Kmeans
     variationsWithin:
       - name: clusterParams
         subName: eps
         values: [0.05, 0.1, 0.15, 0.2]
     priorityLine: [eps]
     unifyByRecursionLevels: [1]
     clustering: True
     clusterFunction: dbscan
     clusterParams:
       eps: 0
     dataset: 'src/data/pd_speech_features.csv'
     classname: class
     nanStrategy: most_frequent
     rescaler: normalize
     correlationThreshold: 0.85
     featureFunction: f_classif
     featuresToKeepPercentage: 0.01
     PCA: False
     patternMining: False
     plotX: 'eps'
