name: dbscan threshold
clustering: True
clusterFunction: dbscan
dataset: 'src/data/pd_speech_features.csv'
classname: class
nanStrategy: most_frequent
rescaler: normalize
correlationThreshold: 0.01
PCA: False
dataSplitMethod: 'kfold'
kFold: 5
patternMining: True
featureFunction: f_classif
nFeatures: 10
saveModel: False
plotX: n_neighbors
# miningParams:
#   supportThreshold: 2
#   supportConfidence: 0.8
percComponentsPCA: 0.7
# Functionality
clusterFunction: dbscan
clustering: False
clusterParams:
  n_clusters: 2
