# Main params
dataset: 'src/data/pd_speech_features.csv'
# dataset: 'src/data/covtype.data'
classname: class
classifier: decisionTree
    classifierParams:
      criterion: 'gini'
      max_depth: 1
nanStrategy: most_frequent
balancingStrategy: notBalanced
rescaler: normalize
correlationThreshold: 1
PCA: False
dataSplitMethod: 'kfold'  # 'kfold'
kFold: 10
patternMining: False
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
clustering: False
clusterParams:
  nclusters: 2
