# Main params
dataset: 'src/data/pd_speech_features.csv'
# dataset: 'src/data/covtype.data'
classname: class
classifier: naiveBays
# Preparation
nanStrategy: most_frequent
balancingStrategy: randUndersample
rescaler: normalize
correlationThreshold: 1
PCA: False
dataSplitMethod: 'kfold'
kFold: 5
patternMining: True
featureFunction: f_classif
nFeatures: 50
saveModel: False
plotX: n_neighbors
# miningParams:
#   supportThreshold: 2
#   supportConfidence: 0.8
percComponentsPCA: 0.7
# Functionality
clusterFunction: dbscan
clustering: False
clusterParams:
  n_clusters: 2