# Main params
dataset: 'src/data/pd_speech_features.csv'
# dataset: 'src/data/covtype.data'
classname: class
classifier: decisionTree
# Preparation
nanStrategy: most_frequent
balancingStrategy: notBalanced
rescaler: normalize
covarianceThreshold: 0.95
PCA: False
percComponentsPCA: 0.7
# Functionality
patternMining: False
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
clusterFunction: kmeans 
clustering: True
clusterParams:
  n_clusters: 2