configs:
   - name: dT(Gini, uniform) - [balancing, max_depth]
     variations:
      - name: balancingStrategy
        values: [notBalanced, randUndersample, smote]
     variationsWithin:
      - name: classifierParams
        subName: max_depth
        values: [1, 3, 5]
     priorityLine: [balancingStrategy, max_depth]
     unifyByRecursionLevels: [1, 0]
     changedToHigherDimPlot:
      level: fetchCSV
      pallets: True
      joinYToLabel: [True, False, False]
      yLabelsLine:  [['Not Balanced', 'Randomly Undersample', 'SMOTE'],
                     ['Not Balanced', 'Randomly Undersample', 'SMOTE'],
                     ['Not Balanced', 'Randomly Undersample', 'SMOTE']]
      yLabelsBox:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
      yLabelsScatter:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
     classifier: decisionTree
     classifierParams:
      criterion: 'gini'
      max_depth: 2
     dataset: 'src/data/pd_speech_features.csv'
     classname: class
     nanStrategy: most_frequent
     rescaler: normalize
     correlationThreshold: 1
     PCA: False
     dataSplitMethod: 'kfold'
     kFold: 10
     clustering: False
     patternMining: False
     plotX: max_depth
   - name: naiveBays (balancing)
     variations:
      - name: balancingStrategy
        values: [notBalanced, randUndersample, smote]
     variationsWithin:
      - name: ''
        subName: ''
        values: []
     priorityLine: [balancingStrategy]
     unifyByRecursionLevels: [1, 0]
     changedToHigherDimPlot:
      level: localCSV
      pallets: True
      joinYToLabel: [True, False, False]
      yLabelsLine:  [['Not Balanced', 'Randomly Undersample', 'SMOTE'],
                     ['Not Balanced', 'Randomly Undersample', 'SMOTE'],
                     ['Not Balanced', 'Randomly Undersample', 'SMOTE']]
      yLabelsBox:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
      yLabelsScatter:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
     classifier: naiveBays
     dataset: 'src/data/pd_speech_features.csv'
     classname: class
     nanStrategy: most_frequent
     rescaler: normalize
     correlationThreshold: 1
     PCA: False
     dataSplitMethod: 'kfold'
     kFold: 10
     clustering: False
     patternMining: False
     plotX: balancingStrategy
