configs:
    - name: Kmode
      variationsWithin:
        - name: clusterParams
          subName: n_clusters
          values: [2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
      priorityLine: [n_clusters]
      unifyByRecursionLevels: [1]
      clustering: True
      clusterFunction: kmeans
      clusterParams:
        n_clusters: 0
      dataset: 'src/data/covtype.data'
      classname: class
      nanStrategy: most_frequent
      rescaler: normalize
      correlationThreshold: 1
      PCA: False
      patternMining: False
      plotX: 'n_clusters'
