configs:
   - name: DBSCAN
     variationsWithin:
       - name: clusterParams
         subName: eps
         values: [1.5, 1.7, 2, 2.2, 2.5, 2.7, 3]
     priorityLine: [eps]
     unifyByRecursionLevels: [1]
     clustering: True
     clusterFunction: dbscan
     clusterParams: 
       eps: 0
     dataset: 'src/data/pd_speech_features.csv'
     classname: class
     nanStrategy: most_frequent
     rescaler: normalize
     correlationThreshold: 1
     PCA: False
     patternMining: False
     plotX: 'eps'