configs:
   - name: pattern mining
     variations:
        - name: typeMiningParams 
          values: [cut, qcut]
     variationsWithin:
        - name: miningParams
          subName: n
          values: [2, 3, 4, 5, 6, 7, 8, 9]
     priorityLine: [typeMiningParams, n]
     changedToHigherDimPlot:
      level: fetchCSV
      pallets: True
      joinYToLabel: [True, False, False]
      yLabelsLine:  ['cut', 'qcut']
      yLabelsBox:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
      yLabelsScatter:  ['Not Balanced', 'Randomly Undersample', 'SMOTE']
     dataset: 'src/data/pd_speech_features.csv'
     classname: class
     nanStrategy: most_frequent
     rescaler: normalize
     correlationThreshold: 1
     PCA: False
     clustering: False
     patternMining: True
     plotX: n
     clusterFunction: kmeans
     clustering: False
     clusterParams:
      n_clusters: 2
     miningParams:
      min_patterns: 30
     featureFunction: f_classif
     nFeatures: 10