configs:
  - # dataset: 'src/data/pd_speech_features.csv'
    dataset: 'src/data/covtype.data'
    classname: class
    classifier: naiveBays
    nanStrategy: most_frequent
    balancingStrategy: notBalanced
    rescaler: normalize
    covarianceThreshold: 1
    clustering: False
    patternMining: False
  - # dataset: 'src/data/pd_speech_features.csv'
    dataset: 'src/data/covtype.data'
    classname: class
    classifier: naiveBays
    nanStrategy: most_frequent
    balancingStrategy: notBalanced
    rescaler: normalize
    covarianceThreshold: .9
    clustering: False
    patternMining: False
  - # dataset: 'src/data/pd_speech_features.csv'
    dataset: 'src/data/covtype.data'
    classname: class
    classifier: naiveBays
    nanStrategy: most_frequent
    balancingStrategy: notBalanced
    rescaler: normalize
    covarianceThreshold: .80
    clustering: False
    patternMining: False
