dataset: 'src/data/pd_speech_features.csv'
# dataset: 'src/data/covtype.data'
classname: class
# classname: consensus
classifier: naiveBays
classifierParams:
  n_neighbors: 5
  weights: 'uniform'    # or 'distance'
  metric: 'euclidean'
nanStrategy: most_frequent
balancingStrategy: notBalanced
rescaler: normalize
covarianceThreshold: 0.95
PCA: False
percComponentsPCA: 0.7
patternMining: False
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
clustering: False
clusterParams:
  nclusters: 2
