# Main params
dataset: 'src/data/covtype.data'
# dataset: 'src/data/covtype.data'
classname: class
classifier: naiveBays
# Preparation
nanStrategy: most_frequent
balancingStrategy: randUndersample
rescaler: normalize
correlationThreshold: 1
PCA: False
dataSplitMethod: 'kfold'
kFold: 5
patternMining: False
featureFunction: f_classif
nFeatures: 10
saveModel: False
plotX: n_neighbors
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
percComponentsPCA: 0.7
# Functionality
clusterFunction: dbscan
clustering: False
clusterParams:
  eps: 5