configs:
   - name: DBSCAN
     variationsWithin:
       - name: clusterParams
         subName: eps
         values: [3, 4, 5, 5.5, 6]
     priorityLine: [eps]
     unifyByRecursionLevels: [1]
     clustering: True
     clusterFunction: dbscan
     clusterParams: 
       eps: 0
     dataset: 'src/data/pd_speech_features.csv'
     PCA: False
