name: dbscan threshold
clustering: True
clusterFunction: dbscan
dataset: 'src/data/pd_speech_features.csv'
classname: class
nanStrategy: most_frequent
rescaler: normalize
correlationThreshold: 0.01
PCA: False
patternMining: False
plotX: 'eps'
clusterParams:
  eps: 1