# Main params
dataset: 'src/data/pd_speech_features.csv'
# dataset: 'src/data/covtype.data'
classname: class
classifier: decisionTree
# Preparation
nanStrategy: most_frequent
balancingStrategy: notBalanced
rescaler: normalize
correlationThreshold: 1
PCA: False
dataSplitMethod: 'kfold'
kFold: 10
patternMining: False
saveModel: False
plotX: n_neighbors
miningParams:
  supportThreshold: 2
  supportConfidence: 0.8
percComponentsPCA: 0.7
# Functionality
clusterFunction: kmeans
clustering: False
clusterParams:
  n_clusters: 2